name 'package'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures package'
long_description 'Installs/Configures package'
version '0.2.0'
